COUNTRY_CODEMAP = {
    'afghanistan': 'AF',
    'aland islands !åland islands': 'AX',
    'albania': 'AL',
    'algeria': 'DZ',
    'american samoa': 'AS',
    'andorra': 'AD',
    'angola': 'AO',
    'anguilla': 'AI',
    'antarctica': 'AQ',
    'antigua and barbuda': 'AG',
    'argentina': 'AR',
    'armenia': 'AM',
    'aruba': 'AW',
    'australia': 'AU',
    'austria': 'AT',
    'azerbaijan': 'AZ',
    'bahamas': 'BS',
    'bahrain': 'BH',
    'bangladesh': 'BD',
    'barbados': 'BB',
    'belarus': 'BY',
    'belgium': 'BE',
    'belize': 'BZ',
    'benin': 'BJ',
    'bermuda': 'BM',
    'bhutan': 'BT',
    'bolivia, plurinational state of': 'BO',
    'bonaire, sint eustatius and saba': 'BQ',
    'bosnia and herzegovina': 'BA',
    'botswana': 'BW',
    'bouvet island': 'BV',
    'brazil': 'BR',
    'british indian ocean territory': 'IO',
    'brunei darussalam': 'BN',
    'bulgaria': 'BG',
    'burkina faso': 'BF',
    'burundi': 'BI',
    'cabo verde': 'CV',
    'cambodia': 'KH',
    'cameroon': 'CM',
    'canada': 'CA',
    'cayman islands': 'KY',
    'central african republic': 'CF',
    'chad': 'TD',
    'chile': 'CL',
    'china': 'CN',
    'christmas island': 'CX',
    'cocos (keeling) islands': 'CC',
    'colombia': 'CO',
    'comoros': 'KM',
    'congo': 'CG',
    'congo, the democratic republic of the': 'CD',
    'cook islands': 'CK',
    'costa rica': 'CR',
    "cote d'ivoire !côte d'ivoire": 'CI',
    'croatia': 'HR',
    'cuba': 'CU',
    'curaçao': 'CW',
    'cyprus': 'CY',
    'czechia': 'CZ',
    'denmark': 'DK',
    'djibouti': 'DJ',
    'dominica': 'DM',
    'dominican republic': 'DO',
    'ecuador': 'EC',
    'egypt': 'EG',
    'el salvador': 'SV',
    'equatorial guinea': 'GQ',
    'eritrea': 'ER',
    'estonia': 'EE',
    'ethiopia': 'ET',
    'falkland islands (malvinas)': 'FK',
    'faroe islands': 'FO',
    'fiji': 'FJ',
    'finland': 'FI',
    'france': 'FR',
    'french guiana': 'GF',
    'french polynesia': 'PF',
    'french southern territories': 'TF',
    'gabon': 'GA',
    'gambia': 'GM',
    'georgia': 'GE',
    'germany': 'DE',
    'ghana': 'GH',
    'gibraltar': 'GI',
    'greece': 'GR',
    'greenland': 'GL',
    'grenada': 'GD',
    'guadeloupe': 'GP',
    'guam': 'GU',
    'guatemala': 'GT',
    'guernsey': 'GG',
    'guinea': 'GN',
    'guinea-bissau': 'GW',
    'guyana': 'GY',
    'haiti': 'HT',
    'heard island and mcdonald islands': 'HM',
    'holy see': 'VA',
    'honduras': 'HN',
    'hong kong': 'HK',
    'hungary': 'HU',
    'iceland': 'IS',
    'india': 'IN',
    'indonesia': 'ID',
    'iran, islamic republic of': 'IR',
    'iraq': 'IQ',
    'ireland': 'IE',
    'isle of man': 'IM',
    'israel': 'IL',
    'italy': 'IT',
    'jamaica': 'JM',
    'japan': 'JP',
    'jersey': 'JE',
    'jordan': 'JO',
    'kazakhstan': 'KZ',
    'kenya': 'KE',
    'kiribati': 'KI',
    "korea, democratic people's republic of": 'KP',
    'korea, republic of': 'KR',
    'kuwait': 'KW',
    'kyrgyzstan': 'KG',
    "lao people's democratic republic": 'LA',
    'latvia': 'LV',
    'lebanon': 'LB',
    'lesotho': 'LS',
    'liberia': 'LR',
    'libya': 'LY',
    'liechtenstein': 'LI',
    'lithuania': 'LT',
    'luxembourg': 'LU',
    'macao': 'MO',
    'macedonia, the former yugoslav republic of': 'MK',
    'madagascar': 'MG',
    'malawi': 'MW',
    'malaysia': 'MY',
    'maldives': 'MV',
    'mali': 'ML',
    'malta': 'MT',
    'marshall islands': 'MH',
    'martinique': 'MQ',
    'mauritania': 'MR',
    'mauritius': 'MU',
    'mayotte': 'YT',
    'mexico': 'MX',
    'micronesia, federated states of': 'FM',
    'moldova, republic of': 'MD',
    'monaco': 'MC',
    'mongolia': 'MN',
    'montenegro': 'ME',
    'montserrat': 'MS',
    'morocco': 'MA',
    'mozambique': 'MZ',
    'myanmar': 'MM',
    'namibia': 'NA',
    'nauru': 'NR',
    'nepal': 'NP',
    'netherlands': 'NL',
    'new caledonia': 'NC',
    'new zealand': 'NZ',
    'nicaragua': 'NI',
    'niger': 'NE',
    'nigeria': 'NG',
    'niue': 'NU',
    'norfolk island': 'NF',
    'northern mariana islands': 'MP',
    'norway': 'NO',
    'oman': 'OM',
    'pakistan': 'PK',
    'palau': 'PW',
    'palestine, state of': 'PS',
    'panama': 'PA',
    'papua new guinea': 'PG',
    'paraguay': 'PY',
    'peru': 'PE',
    'philippines': 'PH',
    'pitcairn': 'PN',
    'poland': 'PL',
    'portugal': 'PT',
    'puerto rico': 'PR',
    'qatar': 'QA',
    'reunion !réunion': 'RE',
    'romania': 'RO',
    'russian federation': 'RU',
    'rwanda': 'RW',
    'saint barthélemy': 'BL',
    'saint helena, ascension and tristan da cunha': 'SH',
    'saint kitts and nevis': 'KN',
    'saint lucia': 'LC',
    'saint martin (french part)': 'MF',
    'saint pierre and miquelon': 'PM',
    'saint vincent and the grenadines': 'VC',
    'samoa': 'WS',
    'san marino': 'SM',
    'sao tome and principe': 'ST',
    'saudi arabia': 'SA',
    'senegal': 'SN',
    'serbia': 'RS',
    'seychelles': 'SC',
    'sierra leone': 'SL',
    'singapore': 'SG',
    'sint maarten (dutch part)': 'SX',
    'slovakia': 'SK',
    'slovenia': 'SI',
    'solomon islands': 'SB',
    'somalia': 'SO',
    'south africa': 'ZA',
    'south georgia and the south sandwich islands': 'GS',
    'south sudan': 'SS',
    'spain': 'ES',
    'sri lanka': 'LK',
    'sudan': 'SD',
    'suriname': 'SR',
    'svalbard and jan mayen': 'SJ',
    'swaziland': 'SZ',
    'sweden': 'SE',
    'switzerland': 'CH',
    'syrian arab republic': 'SY',
    'taiwan, province of china': 'TW',
    'tajikistan': 'TJ',
    'tanzania, united republic of': 'TZ',
    'thailand': 'TH',
    'timor-leste': 'TL',
    'togo': 'TG',
    'tokelau': 'TK',
    'tonga': 'TO',
    'trinidad and tobago': 'TT',
    'tunisia': 'TN',
    'turkey': 'TR',
    'turkmenistan': 'TM',
    'turks and caicos islands': 'TC',
    'tuvalu': 'TV',
    'uganda': 'UG',
    'ukraine': 'UA',
    'united arab emirates': 'AE',
    'united kingdom of great britain and northern ireland': 'GB',
    'united states minor outlying islands': 'UM',
    'united states of america': 'US',
    'uruguay': 'UY',
    'uzbekistan': 'UZ',
    'vanuatu': 'VU',
    'venezuela, bolivarian republic of': 'VE',
    'viet nam': 'VN',
    'virgin islands, british': 'VG',
    'virgin islands, u.s.': 'VI',
    'wallis and futuna': 'WF',
    'western sahara': 'EH',
    'yemen': 'YE',
    'zambia': 'ZM',
    'zimbabwe': 'ZW'
}

COUNTRY_CODES = set(COUNTRY_CODEMAP.values())

LANGUAGE_CODEMAP = {
    'abkhaz': 'ab',
    'afar': 'aa',
    'afrikaans': 'af',
    'akan': 'ak',
    'albanian': 'sq',
    'amharic': 'am',
    'arabic': 'ar',
    'aragonese': 'an',
    'armenian': 'hy',
    'assamese': 'as',
    'avaric': 'av',
    'avestan': 'ae',
    'aymara': 'ay',
    'azerbaijani': 'az',
    'bambara': 'bm',
    'bashkir': 'ba',
    'basque': 'eu',
    'belarusian': 'be',
    'bengali, bangla': 'bn',
    'bihari': 'bh',
    'bislama': 'bi',
    'bosnian': 'bs',
    'breton': 'br',
    'bulgarian': 'bg',
    'burmese': 'my',
    'catalan': 'ca',
    'chamorro': 'ch',
    'chechen': 'ce',
    'chichewa, chewa, nyanja': 'ny',
    'chinese': 'zh',
    'chuvash': 'cv',
    'cornish': 'kw',
    'corsican': 'co',
    'cree': 'cr',
    'croatian': 'hr',
    'czech': 'cs',
    'danish': 'da',
    'divehi, dhivehi, maldivian': 'dv',
    'dutch': 'nl',
    'dzongkha': 'dz',
    'eastern punjabi, eastern panjabi': 'pa',
    'english': 'en',
    'esperanto': 'eo',
    'estonian': 'et',
    'ewe': 'ee',
    'faroese': 'fo',
    'fijian': 'fj',
    'finnish': 'fi',
    'french': 'fr',
    'fula, fulah, pulaar, pular': 'ff',
    'galician': 'gl',
    'ganda': 'lg',
    'georgian': 'ka',
    'german': 'de',
    'greek (modern)': 'el',
    'guaraní': 'gn',
    'gujarati': 'gu',
    'haitian, haitian creole': 'ht',
    'hausa': 'ha',
    'hebrew (modern)': 'he',
    'herero': 'hz',
    'hindi': 'hi',
    'hiri motu': 'ho',
    'hungarian': 'hu',
    'icelandic': 'is',
    'ido': 'io',
    'igbo': 'ig',
    'indonesian': 'id',
    'interlingua': 'ia',
    'interlingue': 'ie',
    'inuktitut': 'iu',
    'inupiaq': 'ik',
    'irish': 'ga',
    'italian': 'it',
    'japanese': 'ja',
    'javanese': 'jv',
    'kalaallisut, greenlandic': 'kl',
    'kannada': 'kn',
    'kanuri': 'kr',
    'kashmiri': 'ks',
    'kazakh': 'kk',
    'khmer': 'km',
    'kikuyu, gikuyu': 'ki',
    'kinyarwanda': 'rw',
    'kirundi': 'rn',
    'komi': 'kv',
    'kongo': 'kg',
    'korean': 'ko',
    'kurdish': 'ku',
    'kwanyama, kuanyama': 'kj',
    'kyrgyz': 'ky',
    'lao': 'lo',
    'latin': 'la',
    'latvian': 'lv',
    'limburgish, limburgan, limburger': 'li',
    'lingala': 'ln',
    'lithuanian': 'lt',
    'luba-katanga': 'lu',
    'luxembourgish, letzeburgesch': 'lb',
    'macedonian': 'mk',
    'malagasy': 'mg',
    'malay': 'ms',
    'malayalam': 'ml',
    'maltese': 'mt',
    'manx': 'gv',
    'marathi (marāṭhī)': 'mr',
    'marshallese': 'mh',
    'mongolian': 'mn',
    'māori': 'mi',
    'nauruan': 'na',
    'navajo, navaho': 'nv',
    'ndonga': 'ng',
    'nepali': 'ne',
    'northern ndebele': 'nd',
    'northern sami': 'se',
    'norwegian': 'no',
    'norwegian bokmål': 'nb',
    'norwegian nynorsk': 'nn',
    'nuosu': 'ii',
    'occitan': 'oc',
    'ojibwe, ojibwa': 'oj',
    'old church slavonic, church slavonic, old bulgarian': 'cu',
    'oriya': 'or',
    'oromo': 'om',
    'ossetian, ossetic': 'os',
    'pashto, pushto': 'ps',
    'persian (farsi)': 'fa',
    'polish': 'pl',
    'portuguese': 'pt',
    'pāli': 'pi',
    'quechua': 'qu',
    'romanian': 'ro',
    'romansh': 'rm',
    'russian': 'ru',
    'samoan': 'sm',
    'sango': 'sg',
    'sanskrit (saṁskṛta)': 'sa',
    'sardinian': 'sc',
    'scottish gaelic, gaelic': 'gd',
    'serbian': 'sr',
    'shona': 'sn',
    'sindhi': 'sd',
    'sinhalese, sinhala': 'si',
    'slovak': 'sk',
    'slovene': 'sl',
    'somali': 'so',
    'southern ndebele': 'nr',
    'southern sotho': 'st',
    'spanish': 'es',
    'sundanese': 'su',
    'swahili': 'sw',
    'swati': 'ss',
    'swedish': 'sv',
    'tagalog': 'tl',
    'tahitian': 'ty',
    'tajik': 'tg',
    'tamil': 'ta',
    'tatar': 'tt',
    'telugu': 'te',
    'thai': 'th',
    'tibetan standard, tibetan, central': 'bo',
    'tigrinya': 'ti',
    'tonga (tonga islands)': 'to',
    'tsonga': 'ts',
    'tswana': 'tn',
    'turkish': 'tr',
    'turkmen': 'tk',
    'twi': 'tw',
    'ukrainian': 'uk',
    'urdu': 'ur',
    'uyghur': 'ug',
    'uzbek': 'uz',
    'venda': 've',
    'vietnamese': 'vi',
    'volapük': 'vo',
    'walloon': 'wa',
    'welsh': 'cy',
    'western frisian': 'fy',
    'wolof': 'wo',
    'xhosa': 'xh',
    'yiddish': 'yi',
    'yoruba': 'yo',
    'zhuang, chuang': 'za',
    'zulu': 'zu'
}

LANGUAGE_CODES = set(LANGUAGE_CODEMAP.values())

